import Link from "next/link";
import { AgendaDemo } from "@/components/marketing/agenda-demo";
import { Check, ChevronRight, LockKeyhole } from "lucide-react";

const features = [
  ["Agenda organizada", "Veja os horários, bloqueios e atendimentos em uma única rotina."],
  ["Clientes centralizados", "Contatos e histórico organizados para encontrar o que precisa."],
  ["Menos conflitos", "A disponibilidade é validada no servidor antes de confirmar a vaga."],
  ["Gestão simples", "Serviços, duração, valores e horários sem planilhas improvisadas."],
  ["Em qualquer dispositivo", "Uma experiência pensada para a correria do celular e para o desktop."],
  ["Pronto para equipes", "Acessos individuais para quem cuida da rotina com você."],
];

export default function HomePage() {
  return <main className="marketing-page">
    <header className="marketing-header"><Link className="saas-logo" href="/">agenda<span>.</span></Link><nav aria-label="Navegação principal"><a href="#recursos">Recursos</a><a href="#como-funciona">Como funciona</a><a href="#para-quem">Para quem é</a><a href="#seguranca">Segurança</a><a href="#planos">Planos</a><a href="#faq">FAQ</a></nav><div className="marketing-actions"><Link href="/login">Entrar</Link><Link className="button button-primary" href="/cadastro">Criar conta grátis</Link></div></header>
    <section className="marketing-hero" id="inicio"><div><p className="eyebrow">AGENDA PARA NEGÓCIOS DE ATENDIMENTO</p><h1>Organize sua agenda.<br />Simplifique seu atendimento.</h1><p className="hero-lead">Uma plataforma para centralizar horários, clientes, serviços e a rotina do seu negócio — sem complicar o que precisa ser simples.</p><div className="hero-actions"><Link className="button button-primary" href="/cadastro">Começar gratuitamente <ChevronRight size={18} /></Link><a className="button button-quiet" href="#recursos">Conhecer recursos</a></div><p className="hero-proof"><Check size={16} /> Sem cartão. Acesso gratuito nesta fase.</p></div><AgendaDemo /></section>
    <section className="marketing-section benefits" id="recursos"><div className="section-kicker"><p className="eyebrow">O ESSENCIAL, BEM RESOLVIDO</p><h2>Menos esforço para administrar. Mais presença no atendimento.</h2></div><div className="benefit-grid">{features.map(([title, description], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section className="marketing-section split-section"><div><p className="eyebrow">RECURSOS DISPONÍVEIS</p><h2>Uma agenda operacional de verdade.</h2><ul className="check-list"><li><Check />Agenda diária com grade configurável</li><li><Check />Clientes, serviços e histórico</li><li><Check />Disponibilidade, bloqueios e exceções</li><li><Check />Status, confirmação, cancelamento e reagendamento</li><li><Check />Instalação como aplicativo pelo navegador</li><li><Check />Despesas, pacotes e fechamento diário</li></ul></div><div className="future-list"><p className="eyebrow">EM PREPARAÇÃO</p><h3>O que vem a seguir</h3><p>Relatórios avançados, página pública de agendamento por negócio, notificações por WhatsApp, integrações de pagamento e controles de plano serão liberados gradualmente.</p><p>Não apresentamos essas funções como disponíveis antes de estarem prontas.</p></div></section>
    <section className="marketing-section how-section" id="como-funciona"><p className="eyebrow">COMO FUNCIONA</p><h2>Da conta à primeira agenda em poucos passos.</h2><ol>{["Crie sua conta", "Configure seu negócio", "Cadastre seus serviços", "Defina os horários", "Organize seus atendimentos"].map((item, index) => <li key={item}><span>{index + 1}</span>{item}</li>)}</ol></section>
    <section className="marketing-section audience-section" id="para-quem"><p className="eyebrow">FEITO PARA ATENDIMENTO</p><h2>Flexível para quem trabalha com agenda.</h2><div>{["Salões de beleza", "Designers de sobrancelhas", "Lash designers", "Manicures", "Esteticistas", "Maquiadores", "Cabeleireiros", "Barbearias", "Profissionais autônomos", "Pequenos studios", "Clínicas de estética"].map((item) => <span key={item}>{item}</span>)}</div></section>
    <section className="marketing-section security-section" id="seguranca"><LockKeyhole size={28} /><div><p className="eyebrow">SEGURANÇA E PRIVACIDADE</p><h2>Dados separados, acesso controlado.</h2><p>Os dados do seu negócio ficam separados dos demais. Cada pessoa da equipe acessa apenas o que seu perfil permite, com verificações no servidor e proteção das contas.</p><Link href="/privacidade">Ler política de privacidade</Link></div></section>
    <section className="marketing-section plans-section" id="planos"><p className="eyebrow">PLANOS</p><h2>Comece sem compromisso.</h2><article><span>Acesso antecipado</span><h3>Use gratuitamente nesta fase.</h3><p>Sem cartão e sem bloqueio de recursos enquanto construímos a melhor base para seu negócio.</p><Link className="button button-primary" href="/cadastro">Começar gratuitamente</Link></article><p className="plans-note">Planos pagos poderão ser oferecidos no futuro. Por enquanto, aproveite o acesso gratuito.</p></section>
    <section className="marketing-section faq-section" id="faq"><p className="eyebrow">DÚVIDAS FREQUENTES</p><h2>Respostas diretas antes de começar.</h2><div>{[["Preciso instalar alguma coisa?", "Não é obrigatório. Use pelo navegador ou instale em Configurações → Instalar aplicativo."],["Funciona no celular?", "Sim. As telas operacionais são responsivas e priorizam os fluxos do dia a dia."],["Posso usar gratuitamente?", "Sim, nesta fase de acesso antecipado não há cartão nem cobrança obrigatória."],["É indicado apenas para salões?", "Não. A estrutura atende profissionais e equipes que trabalham com horários."],["Meus dados ficam separados?", "Sim. Os dados operacionais são vinculados à organização e filtrados no servidor."],["Vai existir plano pago?", "A arquitetura está preparada para isso, mas não há cobrança ativa agora."]].map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
    <footer className="marketing-footer"><div><Link className="saas-logo" href="/">agenda<span>.</span></Link><p>Agenda e operação para negócios que atendem pessoas.</p></div><div><Link href="#recursos">Recursos</Link><Link href="#seguranca">Segurança</Link><Link href="/termos">Termos</Link><Link href="/privacidade">Privacidade</Link></div><div><Link href="/login">Entrar</Link><Link href="/cadastro">Criar conta</Link></div></footer>
  </main>;
}
