"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { assertSameOrigin, requirePermission } from "@/lib/auth/session";
import { closeDailyCash, createExpense, createServicePackage, FinanceError } from "@/lib/admin/finance";
export type FinanceFormState = { error?: string; success?: string };
const cents = (value: FormDataEntryValue | null) => Math.round(Number(String(value ?? "").replace(/\./g, "").replace(",", ".")) * 100);
export async function createExpenseAction(_: FinanceFormState, formData: FormData): Promise<FinanceFormState> { await assertSameOrigin(); const user = await requirePermission("FINANCE_MANAGE"); const category = z.string().trim().min(2).max(80).safeParse(formData.get("category")); const description = z.string().trim().min(2).max(240).safeParse(formData.get("description")); const amountCents = cents(formData.get("amount")); const date = z.string().date().safeParse(formData.get("date")); const method = z.enum(["CASH", "PIX", "CARD", "TRANSFER"]).safeParse(formData.get("method")); if (!category.success || !description.success || !date.success || !method.success || !Number.isInteger(amountCents)) return { error: "Revise os dados da despesa." }; try { await createExpense({ category: category.data, description: description.data, amountCents, occurredAt: new Date(`${date.data}T12:00:00Z`), paymentMethod: method.data, note: String(formData.get("note") ?? "").trim() || null, actorUserId: user.id }); revalidatePath("/admin/financeiro"); return { success: "Despesa registrada." }; } catch (error) { return { error: error instanceof FinanceError ? error.message : "Não foi possível registrar a despesa." }; } }
export async function createPackageAction(_: FinanceFormState, formData: FormData): Promise<FinanceFormState> { await assertSameOrigin(); const user = await requirePermission("FINANCE_MANAGE"); const clientId = z.string().cuid().safeParse(formData.get("clientId")); const serviceId = z.string().cuid().safeParse(formData.get("serviceId")); const name = z.string().trim().min(2).max(140).safeParse(formData.get("name")); const sessions = z.coerce.number().int().min(1).max(999).safeParse(formData.get("sessions")); if (!clientId.success || !serviceId.success || !name.success || !sessions.success) return { error: "Revise os dados do pacote." }; try { await createServicePackage({ clientId: clientId.data, serviceId: serviceId.data, name: name.data, totalSessions: sessions.data, priceCents: formData.get("price") ? cents(formData.get("price")) : null, expiresAt: formData.get("expiresAt") ? new Date(`${String(formData.get("expiresAt"))}T12:00:00Z`) : null, actorUserId: user.id }); revalidatePath("/admin/financeiro"); return { success: "Pacote criado. As sessões serão baixadas ao concluir o atendimento." }; } catch (error) { return { error: error instanceof FinanceError ? error.message : "Não foi possível criar o pacote." }; } }
export async function closeCashAction(_: FinanceFormState, formData: FormData): Promise<FinanceFormState> { await assertSameOrigin(); const user = await requirePermission("FINANCE_CLOSE"); const date = z.string().date().safeParse(formData.get("date")); const actualCents = cents(formData.get("actual")); if (!date.success || !Number.isInteger(actualCents)) return { error: "Revise o fechamento." }; try { await closeDailyCash({ date: new Date(`${date.data}T12:00:00Z`), actualCents, note: String(formData.get("note") ?? "").trim() || null, actorUserId: user.id }); revalidatePath("/admin/financeiro"); return { success: "Fechamento diário salvo." }; } catch (error) { return { error: error instanceof FinanceError ? error.message : "Não foi possível fechar o caixa." }; } }
