"use server";
import { redirect } from "next/navigation";
import { z } from "zod";
import { assertSameOrigin, createSession } from "@/lib/auth/session";
import { hashPassword } from "@/lib/auth/password";
import { getSystemPrisma } from "@/lib/db/prisma";
import { sha256 } from "@/lib/security/hash";
export type ResetAccountState = { error?: string };
const schema = z.object({ token: z.string().regex(/^[A-Za-z0-9_-]{40,60}$/), password: z.string().min(10).max(128).regex(/[a-z]/).regex(/[A-Z]/).regex(/\d/), confirmPassword: z.string() }).refine((value) => value.password === value.confirmPassword, { path: ["confirmPassword"], message: "As senhas não conferem." });
export async function resetAccountPasswordAction(_: ResetAccountState, formData: FormData): Promise<ResetAccountState> { await assertSameOrigin(); const parsed = schema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? "Revise sua nova senha." }; const prisma = getSystemPrisma(); const passwordHash = await hashPassword(parsed.data.password); try { const session = await prisma.$transaction(async (tx) => { const token = await tx.userPasswordResetToken.findUnique({ where: { tokenHash: sha256(parsed.data.token) } }); if (!token || token.usedAt || token.expiresAt <= new Date()) throw new Error("INVALID_TOKEN"); const consumed = await tx.userPasswordResetToken.updateMany({ where: { id: token.id, usedAt: null }, data: { usedAt: new Date() } }); if (consumed.count !== 1) throw new Error("INVALID_TOKEN"); await tx.user.update({ where: { id: token.userId }, data: { passwordHash } }); await tx.session.deleteMany({ where: { userId: token.userId } }); const membership = await tx.organizationMembership.findFirst({ where: { userId: token.userId, isActive: true }, orderBy: { createdAt: "asc" } }); return { userId: token.userId, organizationId: membership?.organizationId }; }); await createSession(session.userId, session.organizationId); } catch (error) { return { error: error instanceof Error && error.message === "INVALID_TOKEN" ? "Este link expirou ou já foi utilizado." : "Não foi possível atualizar a senha agora." }; } redirect("/admin"); }
